"""created product discounts table

Revision ID: 1920186fabd0
Revises: 96190e639cbd
Create Date: 2021-12-06 08:39:20.656192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1920186fabd0'
down_revision = '96190e639cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('value', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_discounts')
    # ### end Alembic commands ###
